// <auto-generated />
using System;
using BasePlate.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BasePlate.Infrastructure.Migrations
{
    [DbContext(typeof(BasePlateDbContext))]
    [Migration("20260820085543_MenuModifiersSetup")]
    partial class MenuModifiersSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllergeneIngrediente", b =>
                {
                    b.Property<int>("AllergeniId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientiId")
                        .HasColumnType("integer");

                    b.HasKey("AllergeniId", "IngredientiId");

                    b.HasIndex("IngredientiId");

                    b.ToTable("AllergeneIngrediente");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Allergene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Allergeni");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.GruppoModificatore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InternalDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxSelections")
                        .HasColumnType("integer");

                    b.Property<int>("MinSelections")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GruppiModificatori");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Ingredienti");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.OpzioneModificatore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GruppoModificatoreId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Sovrapprezzo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GruppoModificatoreId");

                    b.ToTable("OpzioniModificatore");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Prodotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImmagineUrl")
                        .HasColumnType("text");

                    b.Property<int?>("IngredienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.ProdottoAllergene", b =>
                {
                    b.Property<int>("ProdottoId")
                        .HasColumnType("integer");

                    b.Property<int>("AllergeneId")
                        .HasColumnType("integer");

                    b.HasKey("ProdottoId", "AllergeneId");

                    b.HasIndex("AllergeneId");

                    b.ToTable("ProdottoAllergene");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.ProdottoGruppoModificatore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GruppoModificatoreId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrdineVisualizzazione")
                        .HasColumnType("integer");

                    b.Property<int>("ProdottoId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GruppoModificatoreId");

                    b.HasIndex("ProdottoId", "GruppoModificatoreId")
                        .IsUnique();

                    b.ToTable("ProdottoGruppiModificatori");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.ProdottoIngrediente", b =>
                {
                    b.Property<int>("ProdottoId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("integer");

                    b.HasKey("ProdottoId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("ProdottoIngrediente");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Ristorante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorePrimario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DominioPersonalizzato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartitaIva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemaLayout")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ristoranti");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("AllergeneIngrediente", b =>
                {
                    b.HasOne("BasePlate.Core.Entities.Allergene", null)
                        .WithMany()
                        .HasForeignKey("AllergeniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasePlate.Core.Entities.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredientiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BasePlate.Core.Entities.OpzioneModificatore", b =>
                {
                    b.HasOne("BasePlate.Core.Entities.GruppoModificatore", "Gruppo")
                        .WithMany("Opzioni")
                        .HasForeignKey("GruppoModificatoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gruppo");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Prodotto", b =>
                {
                    b.HasOne("BasePlate.Core.Entities.Categoria", "Categoria")
                        .WithMany("Prodotti")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasePlate.Core.Entities.Ingrediente", null)
                        .WithMany("Prodotti")
                        .HasForeignKey("IngredienteId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.ProdottoAllergene", b =>
                {
                    b.HasOne("BasePlate.Core.Entities.Allergene", "Allergene")
                        .WithMany()
                        .HasForeignKey("AllergeneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasePlate.Core.Entities.Prodotto", "Prodotto")
                        .WithMany("Allergeni")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergene");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.ProdottoGruppoModificatore", b =>
                {
                    b.HasOne("BasePlate.Core.Entities.GruppoModificatore", "GruppoModificatore")
                        .WithMany("ProdottiAssociati")
                        .HasForeignKey("GruppoModificatoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasePlate.Core.Entities.Prodotto", "Prodotto")
                        .WithMany("GruppiModificatori")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GruppoModificatore");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.ProdottoIngrediente", b =>
                {
                    b.HasOne("BasePlate.Core.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasePlate.Core.Entities.Prodotto", "Prodotto")
                        .WithMany("Ingredienti")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Utente", b =>
                {
                    b.HasOne("BasePlate.Core.Entities.Ristorante", "Ristorante")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ristorante");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Categoria", b =>
                {
                    b.Navigation("Prodotti");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.GruppoModificatore", b =>
                {
                    b.Navigation("Opzioni");

                    b.Navigation("ProdottiAssociati");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Ingrediente", b =>
                {
                    b.Navigation("Prodotti");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Prodotto", b =>
                {
                    b.Navigation("Allergeni");

                    b.Navigation("GruppiModificatori");

                    b.Navigation("Ingredienti");
                });
#pragma warning restore 612, 618
        }
    }
}
