// <auto-generated />
using System;
using BasePlate.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BasePlate.Infrastructure.Migrations
{
    [DbContext(typeof(BasePlateDbContext))]
    partial class BasePlateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllergeneIngrediente", b =>
                {
                    b.Property<int>("AllergeniId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientiId")
                        .HasColumnType("integer");

                    b.HasKey("AllergeniId", "IngredientiId");

                    b.HasIndex("IngredientiId");

                    b.ToTable("AllergeneIngrediente");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Allergene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Allergeni");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Ingredienti");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Prodotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TipologiaCotturaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TipologiaCotturaId");

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.TipologiaCottura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TipologieCottura");
                });

            modelBuilder.Entity("IngredienteProdotto", b =>
                {
                    b.Property<int>("IngredientiId")
                        .HasColumnType("integer");

                    b.Property<int>("ProdottiId")
                        .HasColumnType("integer");

                    b.HasKey("IngredientiId", "ProdottiId");

                    b.HasIndex("ProdottiId");

                    b.ToTable("IngredienteProdotto");
                });

            modelBuilder.Entity("AllergeneIngrediente", b =>
                {
                    b.HasOne("BasePlate.Core.Entities.Allergene", null)
                        .WithMany()
                        .HasForeignKey("AllergeniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasePlate.Core.Entities.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredientiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Prodotto", b =>
                {
                    b.HasOne("BasePlate.Core.Entities.Categoria", "Categoria")
                        .WithMany("Prodotti")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasePlate.Core.Entities.TipologiaCottura", "TipologiaCottura")
                        .WithMany("Prodotti")
                        .HasForeignKey("TipologiaCotturaId");

                    b.Navigation("Categoria");

                    b.Navigation("TipologiaCottura");
                });

            modelBuilder.Entity("IngredienteProdotto", b =>
                {
                    b.HasOne("BasePlate.Core.Entities.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredientiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasePlate.Core.Entities.Prodotto", null)
                        .WithMany()
                        .HasForeignKey("ProdottiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BasePlate.Core.Entities.Categoria", b =>
                {
                    b.Navigation("Prodotti");
                });

            modelBuilder.Entity("BasePlate.Core.Entities.TipologiaCottura", b =>
                {
                    b.Navigation("Prodotti");
                });
#pragma warning restore 612, 618
        }
    }
}
